# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 24) do

  create_table "comments", :force => true do |t|
    t.column "content",      :text
    t.column "user_id",      :integer,  :null => false
    t.column "page_id",      :integer,  :null => false
    t.column "parent_id",    :integer
    t.column "created_at",   :datetime, :null => false
    t.column "updated_at",   :datetime, :null => false
    t.column "emailupdates", :boolean
  end

  create_table "pages", :force => true do |t|
    t.column "title",        :string,   :null => false
    t.column "content",      :text
    t.column "content_html", :text
    t.column "created_at",   :datetime
    t.column "locked_by",    :integer
  end

  create_table "revisions", :force => true do |t|
    t.column "page_id",    :integer,                :default => 0, :null => false
    t.column "user_id",    :integer,                               :null => false
    t.column "ip",         :string,   :limit => 60
    t.column "created_at", :datetime,                              :null => false
    t.column "updated_at", :datetime,                              :null => false
    t.column "content",    :text
    t.column "addchars",   :integer
    t.column "delchars",   :integer
    t.column "comment",    :string
  end

  create_table "siteinfos", :force => true do |t|
    t.column "name",              :string
    t.column "tagline",           :string
    t.column "template",          :text
    t.column "adminlogin",        :string
    t.column "setup",             :boolean, :default => false
    t.column "email",             :string
    t.column "frontpagecomments", :boolean
  end

  create_table "spammers", :force => true do |t|
    t.column "ip",         :string
    t.column "created_at", :datetime
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "name",                      :string
    t.column "myurl",                     :string
    t.column "aboutme",                   :text
    t.column "admin",                     :boolean
  end

  create_table "votes", :force => true do |t|
    t.column "score",      :integer
    t.column "comment_id", :integer
    t.column "user_id",    :integer
  end

end
